### ISSUE TITLE
Issue generating the weather

### ISSUE THREAD

**Issue by latelylk** [glatteis/poemspublic#1]
When trying to visit /weather I get this error. Error is persistent between tries on MacOS and Debian.

`template: weather_template.html:51:76: executing "weather_template.html" at <index .WeatherTypes 0>: error calling index: reflect: slice index out of range`

**Comment by linusheck** [comment]
This might be an issue that has to do with the weather api. Do you have
your openweathermap login configured?
I also did some changes on my private branch of this over the months, I'll
merge it back into this public one.

Pierce <notifications@github.com> schrieb am Di., 24. Dez. 2019, 06:49:

**Comment by latelylk** [comment]
Weather api is configured and works. The problem seems to happen when generating the site.

**Comment by linusheck** [comment]
This is maybe something that I've already fixed on my private branch and just copied (yes, sorry) into this one. Maybe it works now when you pull and try again? :)

**Comment by latelylk** [comment]
Looks to work, thank you.
